version: "3.13"

services:
  web:
    build: .
    container_name: g3sa_web
    volumes:
      - .:/app
    ports:
      - "2000:2000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:2000