# Generated by Django 5.2.3 on 2025-07-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('logotipo_light', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('logotipo_dark', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('cor_primaria', models.CharField(default='#2c3c9c', max_length=7)),
                ('cor_primaria_texto', models.CharField(default='#ffffff', max_length=7)),
                ('cor_primaria_hover', models.CharField(default='#364cd6', max_length=7)),
                ('cor_secundaria', models.CharField(default='#4b5563', max_length=7)),
                ('cor_background', models.CharField(default='#f9fafb', max_length=7)),
                ('cor_blocos', models.CharField(default='#e5e7eb', max_length=7)),
                ('cor_bordas', models.CharField(default='#d1d5db', max_length=7)),
                ('cor_texto', models.CharField(default='#212937', max_length=7)),
                ('rodape', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
