# Generated by Django 5.2.3 on 2025-06-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('cor_primaria', models.CharField(default='#1f2937', max_length=7)),
                ('rodape', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
