# Generated by Django 5.2.5 on 2025-08-26 15:19

import apps.configuracoes.models.usuario
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nivel_hierarquico', models.IntegerField(default=1)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('logotipo_light', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('logotipo_dark', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('background_img', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('cor_primaria', models.CharField(default='#0c1d41', max_length=7)),
                ('cor_primaria_texto', models.CharField(default='#ffffff', max_length=7)),
                ('cor_primaria_hover', models.CharField(default='#1a3f8d', max_length=7)),
                ('cor_secundaria', models.CharField(default='#ededed', max_length=7)),
                ('cor_background', models.CharField(default='#f9f9fb', max_length=7)),
                ('cor_blocos', models.CharField(default='#ffffff', max_length=7)),
                ('cor_bordas', models.CharField(default='#d1d5db', max_length=7)),
                ('cor_texto', models.CharField(default='#212937', max_length=7)),
                ('cor_texto_hover', models.CharField(default='#1f2937', max_length=7)),
                ('rodape', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_fundacao', models.DateField(blank=True, null=True, verbose_name='Data de Fundação')),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas_logos/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cor_empresa', models.CharField(default='#2c3e50', max_length=7, verbose_name='Cor da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='É Staff?')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.configuracoes.models.usuario.UsuarioPathAndRename(), verbose_name='Foto do Usuário')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('data_contratacao', models.DateField(blank=True, null=True, verbose_name='Data de Contratação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.cargo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('departamento_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_filhos', to='configuracoes.departamento', verbose_name='Departamento Pai')),
                ('supervisor', models.ManyToManyField(blank=True, related_name='departamentos_supervisionados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisores do Departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_por_empresa', to='configuracoes.empresa', verbose_name='Empresa do Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ManyToManyField(blank=True, related_name='usuarios_membros', to='configuracoes.departamento', verbose_name='Departamentos que o usuário participa'),
        ),
    ]
