# Generated by Django 5.2.3 on 2025-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='logotipo',
            new_name='logotipo_dark',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logotipo_light',
            field=models.ImageField(blank=True, null=True, upload_to='logotipos/'),
        ),
    ]
