# Generated by Django 5.2.3 on 2025-07-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_rename_logotipo_empresa_logotipo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_primaria_texto',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_primeira_hover',
            field=models.CharField(default='#374151', max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(default='#4b5563', max_length=7),
        ),
    ]
