# Generated by Django 5.2.3 on 2025-07-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_empresa_cor_primaria_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_background',
            field=models.CharField(default='#f3f4f6', max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_blocos',
            field=models.CharField(default='#e5e7eb', max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_bordas',
            field=models.CharField(default='#d1d5db', max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_texto',
            field=models.CharField(default='#111827', max_length=7),
        ),
    ]
