# Generated by Django 5.2.3 on 2025-07-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_empresa_cor_background_empresa_cor_blocos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cor_primeira_hover',
            new_name='cor_primaria_hover',
        ),
    ]
