# Generated by Django 5.2.3 on 2025-09-02 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Processo')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('vigencia', models.DateTimeField(blank=True, null=True, verbose_name='Vigência')),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('em_revisao', 'Em Revisão'), ('em_mapeamento', 'Em Mapeamento'), ('obsoleto', 'Obsoleto')], default='em_revisao', max_length=20, verbose_name='Status')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_departamento', to='configuracoes.departamento', verbose_name='Departamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='ged_processos.processo', verbose_name='Processo')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ged_processos.processo', verbose_name='Processo')),
            ],
        ),
        migrations.CreateModel(
            name='VersaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('versao', models.CharField(default='1.0', max_length=20, verbose_name='Versão')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='processos_pdfs/', verbose_name='PDF')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='URL do Vídeo')),
                ('data_versao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Versão')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='ged_processos.processo', verbose_name='Processo')),
            ],
        ),
        migrations.CreateModel(
            name='VisualizacaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Visualização')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='ged_processos.processo', verbose_name='Processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
