# Generated by Django 5.2.3 on 2025-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
